# Usamos Nginx para servir archivos estáticos
FROM nginx:stable-alpine

# Directorio donde Nginx sirve los archivos
WORKDIR /usr/share/nginx/html

# Copiamos todo el contenido del frontend al contenedor
COPY . .

# Exponemos el puerto 80
EXPOSE 80
